import type { Dictionary } from './en';

const bs: Dictionary = {
  'app.name': 'Sira',
  'app.tagline': 'Putovanje kroz život Poslanika Muhammeda ﷺ',

  'common.continue': 'Nastavi',
  'common.back': 'Nazad',
  'common.close': 'Zatvori',
  'common.done': 'Gotovo',
  'common.cancel': 'Odustani',
  'common.retry': 'Pokušaj ponovo',
  'common.seeAll': 'Prikaži sve',
  'common.next': 'Dalje',

  'tabs.home': 'Početna',
  'tabs.timeline': 'Hronologija',
  'tabs.map': 'Mapa',
  'tabs.explore': 'Istraži',
  'tabs.profile': 'Profil',

  'onboarding.step': 'Korak {current} od {total}',
  'onboarding.welcome.title': 'Sira',
  'onboarding.welcome.body': 'Putovanje kroz život Poslanika Muhammeda ﷺ – kroz mjesta, ljude, događaje i izvore koji ih čuvaju.',
  'onboarding.seerah.title': 'Šta je sira?',
  'onboarding.seerah.body': 'Sira (es-Sira en-Nebevijja) je životopis Poslanika ﷺ: njegovo rođenje u Mekki, Objava, godine iskušenja, Hidžra u Medinu i osnivanje prve muslimanske zajednice. Muslimani je proučavaju kako bi ga upoznali i učili iz njegovog primjera.',
  'onboarding.how.title': 'Kako putovanje funkcioniše',
  'onboarding.how.body': 'Deset ključnih epizoda, hronologija i interaktivna mapa. Svaka epizoda prolazi kroz šest etapa:',
  'onboarding.loop.explore': 'Istraži',
  'onboarding.loop.explore.desc': 'mjesta, ljude i događaje',
  'onboarding.loop.learn': 'Uči',
  'onboarding.loop.learn.desc': 'šta se desilo – iz izvora',
  'onboarding.loop.connect': 'Poveži',
  'onboarding.loop.connect.desc': 'kako se sve uklapa',
  'onboarding.loop.think': 'Razmisli',
  'onboarding.loop.think.desc': 'uz kratki izazov znanja',
  'onboarding.loop.remember': 'Zapamti',
  'onboarding.loop.remember.desc': 'uz blago ponavljanje',
  'onboarding.loop.reflect': 'Promisli',
  'onboarding.loop.reflect.desc': 'šta to znači za tvoj život',
  'onboarding.sources.title': 'Izvori i tačnost',
  'onboarding.sources.body': 'Ništa u ovoj aplikaciji nije izmišljeno: ni ajeti, ni hadisi, ni razgovori, ni datumi. Svaka epizoda navodi izvore, a svaka tvrdnja je označena:',
  'onboarding.sources.note': 'Gdje se izvori razilaze, aplikacija to i kaže. Poslanik ﷺ nikada nije prikazan ni na jednoj slici.',
  'onboarding.language.title': 'Izaberi jezik',
  'onboarding.language.body': 'Možeš ga kasnije promijeniti u postavkama.',
  'onboarding.start.title': 'Započni putovanje',
  'onboarding.start.body': 'Počni s prvom epizodom – rođenjem i ranim životom Poslanika ﷺ – ili slobodno istražuj.',
  'onboarding.start.cta': 'Pokreni epizodu 1',
  'onboarding.start.later': 'Najprije istraži',

  'kind.fact': 'Utvrđena činjenica',
  'kind.fact.desc': 'Potvrđeno Kur’anom, vjerodostojnim hadisom ili saglasnošću izvora sire.',
  'kind.interpretation': 'Historijsko tumačenje',
  'kind.interpretation.desc': 'Historijsko čitanje, približan datum ili pitanje u kojem se izvori razilaze.',
  'kind.reflection': 'Razmišljanje',
  'kind.reflection.desc': 'Misao ili pouka za tebe – ne historijska tvrdnja.',

  'era.before': 'Prije poslanstva',
  'era.makkah': 'Mekanski period',
  'era.madinah': 'Medinski period',

  'certainty.established': 'Datum potvrđen',
  'certainty.approximate': 'Približan datum',
  'certainty.disputed': 'Datum sporan',

  'home.greeting': 'Es-selamu alejkum',
  'home.continue': 'Nastavi putovanje',
  'home.start': 'Započni putovanje',
  'home.allDone': 'Završio si svih deset epizoda. Možeš im se vratiti kad god želiš.',
  'home.episodeLabel': 'Epizoda {number}',
  'home.progress': 'Napredak u siri',
  'home.episodes': '{done} / {total} epizoda',
  'home.explored': '{percent}% istraženo',
  'home.featured': 'Istaknuti događaj',
  'home.today': 'Današnja sira',
  'home.todayIntro.before': 'Danas istražujemo važan događaj iz godina prije poslanstva.',
  'home.todayIntro.makkah': 'Danas istražujemo važan događaj iz mekanskog perioda.',
  'home.todayIntro.madinah': 'Danas istražujemo važan događaj iz medinskog perioda.',
  'home.learnMore': 'Saznaj više',
  'home.dailyQuestion': 'Pitanje dana',
  'home.dailyDone': 'Odgovoreno danas – sutra stiže novo pitanje.',
  'home.recentPlaces': 'Nedavno istražena mjesta',
  'home.recentNone': 'Mjesta koja otkriješ u epizodama i na mapi pojavit će se ovdje.',
  'home.review': 'Centar za ponavljanje',
  'home.reviewDue': '{count} za ponavljanje',
  'home.reviewNone': 'Ništa nije na redu',
  'home.search': 'Traži osobe, mjesta, događaje…',

  'timeline.title': 'Hronologija',
  'timeline.subtitle': 'Život Poslanika ﷺ redom. Datumi označeni kao približni ili sporni nisu sigurni.',
  'timeline.all': 'Sve',
  'timeline.legend': 'Dodirni događaj da vidiš osobe, mjesta i izvore.',

  'map.title': 'Mapa',
  'map.subtitle': 'Ključna mjesta sire u Hidžazu. Zumiraj s dva prsta ili dugmadima; povuci za pomjeranje.',
  'map.legend': 'Legenda',
  'map.historical': 'Historijska lokacija',
  'map.historical.desc': 'Mjesto je pouzdano poznato.',
  'map.approximate': 'Približna lokacija',
  'map.approximate.desc': 'Tačno mjesto nije sigurno.',
  'map.modern': 'Savremena geografija',
  'map.modern.desc': 'Današnja referentna tačka, samo radi orijentacije.',
  'map.route': 'Put (približan)',
  'map.coast': 'Crveno more – današnja obala (približno)',
  'map.zoomIn': 'Uvećaj',
  'map.zoomOut': 'Umanji',
  'map.reset': 'Vrati prikaz',
  'map.routes': 'Putevi',
  'map.showRoutes': 'Prikaži puteve',
  'map.whyItMatters': 'Zašto je važno',
  'map.events': 'Povezani događaji',
  'map.people': 'Povezane osobe',
  'map.episodes': 'Epizode',
  'map.howKnown': 'Kako znamo gdje se nalazi',
  'map.distance': 'Oko {km} km od Mekke (zračna linija, savremeno mjerenje)',
  'map.openPlace': 'Otvori mjesto',
  'map.offMap': 'Izvan ove mape: {place}',
  'map.label': 'Mapa Hidžaza s {count} lokacija',

  'explore.title': 'Istraži',
  'explore.subtitle': 'Osobe, mjesta, događaji i teme sire – i kako su povezani.',
  'explore.people': 'Osobe',
  'explore.places': 'Mjesta',
  'explore.events': 'Događaji',
  'explore.themes': 'Teme',
  'explore.episodes': 'Epizode',
  'explore.bookmarks': 'Moje oznake',
  'explore.review': 'Centar za ponavljanje',
  'explore.search': 'Pretraga',

  'search.title': 'Pretraga',
  'search.placeholder': 'Traži epizode, osobe, mjesta…',
  'search.hint': 'Probaj „Bilal“, „Hidžra“ ili „Bedr“.',
  'search.empty': 'Ništa nije pronađeno za „{query}“.',
  'search.related': 'Povezano',
  'search.clear': 'Obriši pretragu',

  'type.episode': 'Epizoda',
  'type.event': 'Događaj',
  'type.person': 'Osoba',
  'type.place': 'Mjesto',
  'type.theme': 'Tema',
  'type.source': 'Izvor',

  'connections.title': 'Kako je sve povezano?',
  'connections.subtitle': 'Dodirni karticu da slijediš vezu.',
  'connections.chain': 'Događaj → Osobe → Mjesta → Povezani događaji',

  'episode.label': 'Epizoda {number}',
  'episode.start': 'Pokreni epizodu',
  'episode.continue': 'Nastavi epizodu',
  'episode.restart': 'Istraži ponovo',
  'episode.completed': 'Završeno',
  'episode.bestScore': 'Najbolji rezultat kviza: {percent}%',
  'episode.notFound': 'Ova epizoda nije pronađena.',
  'episode.stepOf': '{current} od {total}',
  'episode.next': 'Dalje',
  'episode.finish': 'Završi epizodu',
  'episode.overview': 'U ovoj epizodi',
  'episode.step.introduction': 'Uvod',
  'episode.step.context': 'Historijski kontekst',
  'episode.step.timeline': 'Hronologija',
  'episode.step.mainEvent': 'Glavni događaj',
  'episode.step.people': 'Uključene osobe',
  'episode.step.locations': 'Lokacije',
  'episode.step.explore': 'Interaktivno istraživanje',
  'episode.step.challenge': 'Izazov znanja',
  'episode.step.lesson': 'Pouke',
  'episode.step.reflection': 'Razmisli o tome',
  'episode.step.sources': 'Izvori',
  'episode.tapToDiscover': 'Dodirni svaku karticu da je otvoriš i dodaš u svoja otkrića.',
  'episode.discovered': 'Otkriveno',
  'episode.mapHint': 'Lokacije ove epizode. Dodirni oznaku da saznaš više.',
  'episode.challengeIntro': '{count} pitanja o ovoj epizodi. Greške se čuvaju za kasnije ponavljanje – nema vremenskog ograničenja.',
  'episode.challengeStart': 'Započni izazov',
  'episode.challengeResult': '{correct} od {total} tačno',
  'episode.challengeRetry': 'Promašena pitanja dodana su u tvoj Centar za ponavljanje.',
  'episode.doneTitle': 'Epizoda završena',
  'episode.doneBody': 'Završio si „{title}“.',
  'episode.points': '+{points} bodova znanja',
  'episode.nextEpisode': 'Sljedeća epizoda',
  'episode.backHome': 'Na početnu',
  'episode.mainEvent': 'Glavni događaj',

  'narration.play': 'Slušaj naraciju',
  'narration.pause': 'Pauziraj naraciju',

  'reflection.title': 'Razmisli o tome',
  'reflection.note': 'Tvoja razmišljanja ostaju na ovom uređaju i nikada se ne ocjenjuju.',
  'reflection.write': 'Zapiši razmišljanje',
  'reflection.select': 'Ili izaberi jedno',
  'reflection.placeholder': 'Tvoje misli…',
  'reflection.save': 'Sačuvaj razmišljanje',
  'reflection.saved': 'Sačuvano',
  'reflection.skip': 'Samo nastavi',
  'reflection.clear': 'Ukloni razmišljanje',

  'sources.primary': 'Primarni izvori',
  'sources.secondary': 'Sekundarni historijski izvori',
  'sources.further': 'Dodatna literatura',
  'sources.open': 'Otvori izvor',
  'sources.openHint': 'Otvara {host} u pregledniku.',
  'source.type.quran': 'Kur’an',
  'source.type.hadith': 'Hadis',
  'source.type.seerah': 'Sira',
  'source.type.history': 'Historija',
  'source.type.biography': 'Biografija',

  'person.role': 'Uloga',
  'person.relationship': 'Odnos',
  'person.biography': 'Biografija',
  'person.events': 'Događaji',
  'person.episodes': 'Epizode',
  'person.notFound': 'Ova osoba nije pronađena.',

  'event.date': 'Datum',
  'event.summary': 'Sažetak',
  'event.people': 'Osobe',
  'event.places': 'Lokacije',
  'event.episode': 'Povezana epizoda',
  'event.related': 'Povezani događaji',
  'event.sources': 'Izvori',
  'event.themes': 'Teme',
  'event.notFound': 'Ovaj događaj nije pronađen.',

  'place.description': 'O ovom mjestu',
  'place.notFound': 'Ovo mjesto nije pronađeno.',
  'place.showOnMap': 'Prikaži na mapi',

  'theme.events': 'Događaji',
  'theme.episodes': 'Epizode',
  'theme.notFound': 'Ova tema nije pronađena.',

  'bookmark.add': 'Dodaj oznaku',
  'bookmark.remove': 'Ukloni oznaku',
  'bookmarks.title': 'Moje oznake',
  'bookmarks.empty': 'Još nema oznaka. Koristi ikonu oznake na epizodama, događajima, osobama, mjestima i izvorima.',

  'review.title': 'Centar za ponavljanje',
  'review.subtitle': 'Promašena pitanja vraćaju se nakon nekog vremena dok ih dobro ne naučiš.',
  'review.needs': 'Za ponavljanje',
  'review.mastered': 'Savladano',
  'review.recent': 'Nedavno naučeno',
  'review.start': 'Ponovi sada ({count})',
  'review.dueNow': 'Na redu sada',
  'review.nextOn': 'Sljedeće ponavljanje: {date}',
  'review.missed': 'Promašeno {count}×',
  'review.emptyNeeds': 'Nema pitanja za ponavljanje. Promašena pitanja iz kviza pojavit će se ovdje.',
  'review.emptyMastered': 'Pitanja koja si više puta uspješno ponovio pojavit će se ovdje.',
  'review.emptyRecent': 'Epizode koje završiš i događaji koje otkriješ u posljednjih 14 dana pojavit će se ovdje.',
  'review.doneTitle': 'Ponavljanje završeno',
  'review.doneBody': 'Zapamtio si {correct} od {total}.',
  'review.nothingDue': 'Trenutno ništa nije na redu.',

  'quiz.correct': 'Tačno',
  'quiz.notQuite': 'Ne baš',
  'quiz.correctAnswer': 'Tačan odgovor: {answer}',
  'quiz.addedToReview': 'Sačuvano u tvom Centru za ponavljanje.',
  'quiz.true': 'Tačno',
  'quiz.false': 'Netačno',
  'quiz.check': 'Provjeri',
  'quiz.ordering.hint': 'Dodirni stavke pravilnim redom.',
  'quiz.ordering.reset': 'Počni ispočetka',
  'quiz.matching.hint': 'Dodirni stavku lijevo, pa njen par desno.',
  'quiz.matching.mistakes': 'Greške: {count}',
  'quiz.question': 'Pitanje {current} od {total}',
  'quiz.kind.general': 'Pitanje',
  'quiz.kind.timeline': 'Poredaj hronološki',
  'quiz.kind.sequence': 'Šta je bilo prvo?',
  'quiz.kind.connection': 'Veza',
  'quiz.kind.personEvent': 'Osoba → Događaj',
  'quiz.kind.placeEvent': 'Mjesto → Događaj',
  'quiz.kind.eventLesson': 'Događaj → Pouka',

  'profile.title': 'Profil',
  'profile.progress': 'Napredak u siri',
  'profile.points': 'Bodovi znanja',
  'profile.completed': 'Završene epizode',
  'profile.noneCompleted': 'Još nijedna epizoda nije završena.',
  'profile.quizResults': 'Rezultati kvizova',
  'profile.noQuiz': 'Tvoji rezultati kvizova pojavit će se ovdje.',
  'profile.badges': 'Značke istraživača',
  'profile.bookmarks': 'Oznake',
  'profile.reflections': 'Razmišljanja',
  'profile.settings': 'Postavke',
  'profile.review': 'Centar za ponavljanje',
  'stats.episodes': 'Epizode',
  'stats.events': 'Otkriveni događaji',
  'stats.people': 'Otkrivene osobe',
  'stats.places': 'Otkrivene lokacije',
  'badges.locked': 'Još nije osvojeno',
  'badges.earned': 'Osvojeno {date}',
  'badge.first_journey.name': 'Prvo putovanje',
  'badge.first_journey.desc': 'Završi svoju prvu epizodu.',
  'badge.makkah_explorer.name': 'Istraživač Mekke',
  'badge.makkah_explorer.desc': 'Završi sve epizode mekanskog perioda.',
  'badge.madinah_explorer.name': 'Istraživač Medine',
  'badge.madinah_explorer.desc': 'Završi sve epizode medinskog perioda.',
  'badge.timeline_explorer.name': 'Istraživač hronologije',
  'badge.timeline_explorer.desc': 'Otkrij svaki događaj na hronologiji.',
  'badge.history_seeker.name': 'Tragač za historijom',
  'badge.history_seeker.desc': 'Otkrij svaku osobu u bazi osoba.',
  'badge.reflective_mind.name': 'Promišljen um',
  'badge.reflective_mind.desc': 'Sačuvaj pet razmišljanja.',
  'badge.seerah_student.name': 'Učenik sire',
  'badge.seerah_student.desc': 'Završi pet epizoda s najmanje 70% u kvizu.',
  'badge.ten_episodes.name': '10 završenih epizoda',
  'badge.ten_episodes.desc': 'Završi svih deset epizoda.',
  'celebrate.title': 'Nova značka',

  'settings.title': 'Postavke',
  'settings.general': 'Općenito',
  'settings.language': 'Jezik',
  'settings.appearance': 'Izgled',
  'settings.theme': 'Tamni način',
  'settings.theme.system': 'Sistem',
  'settings.theme.light': 'Svijetlo',
  'settings.theme.dark': 'Tamno',
  'settings.sound': 'Zvuk',
  'settings.haptics': 'Vibracija',
  'settings.notifications': 'Obavještenja',
  'settings.reminder': 'Dnevni podsjetnik za Današnju siru',
  'settings.reminderDesc': 'Jedan blagi podsjetnik dnevno. Neobavezno – aplikacija u potpunosti radi i bez njega.',
  'settings.reminderTime': 'Vrijeme podsjetnika: {time}',
  'settings.notifDenied': 'Obavještenja su za ovu aplikaciju isključena u sistemskim postavkama.',
  'settings.notifUnavailable': 'Obavještenja nisu dostupna na ovom uređaju.',
  'settings.accessibility': 'Pristupačnost',
  'settings.largeText': 'Veći tekst',
  'settings.highContrast': 'Visoki kontrast',
  'settings.reducedMotion': 'Smanji animacije',
  'settings.info': 'Informacije',
  'settings.about': 'O aplikaciji',
  'settings.privacy': 'Privatnost',
  'settings.sources': 'Izvori',
  'settings.data': 'Podaci',
  'settings.reset': 'Poništi napredak',
  'settings.resetDesc': 'Briše završene epizode, rezultate kvizova, oznake, razmišljanja i otkrića na ovom uređaju.',
  'settings.resetTitle': 'Poništiti sav napredak?',
  'settings.resetBody': 'Ovo se ne može vratiti.',
  'settings.resetConfirm': 'Da, poništi',
  'settings.version': 'Verzija {version}',

  'about.title': 'O aplikaciji Sira',
  'about.p1': 'Sira je besplatna obrazovna aplikacija o životu Poslanika Muhammeda ﷺ za mlade i odrasle. Verzija 1 obuhvata deset ključnih epizoda; nove se mogu dodati bez mijenjanja aplikacije.',
  'about.p2': 'Ne sadrži reklame, kupovine ni korisničke račune i u potpunosti radi bez interneta.',
  'about.p3': 'Aplikacija je uvod, a ne naučni priručnik. Svaka tvrdnja označena je kao utvrđena činjenica, historijsko tumačenje ili razmišljanje, a izvori su navedeni kako bi mogao čitati dalje. Za vjerska pitanja obrati se kvalifikovanim učenjacima.',
  'privacy.title': 'Privatnost',
  'privacy.p1': 'Korisnički račun nije potreban. Lični podaci se ne prikupljaju, ne šalju i ne prodaju. Nema reklama, analitike ni praćenja, a aplikacija ne uspostavlja mrežne veze.',
  'privacy.p2': 'Tvoj napredak, rezultati kvizova, oznake i razmišljanja čuvaju se samo na ovom uređaju. „Poništi napredak“ ih briše. Linkovi izvora otvaraju se u pregledniku samo kada ih dodirneš.',
  'sourcesPage.title': 'Izvori',
  'sourcesPage.p1': 'Sadržaj se zasniva na Kur’anu, zbirkama hadisa Sahih el-Buhari, Sahih Muslim i Sunen Ibn Madže, siri Ibn Hišama (prema Ibn Ishaku), Ibn Sa’du, et-Taberiju, Ibn Kesiru i Ibn el-Kajjimu te savremenim biografijama.',
  'sourcesPage.p2': 'Kur’anski navodi upućuju na quran.com, a Buharijini na sunnah.com. Nijedan izvor nije izmišljen; gdje se pojedinost nije mogla provjeriti, izostavljena je.',
  'sourcesPage.p3': 'Položaji na mapi koriste savremene koordinate. Mjesta čija tačna lokacija nije sigurna označena su kao približna, a putevi su prikazani samo kao opći smjer.',

  'notif.channel': 'Današnja sira',
  'notif.title': 'Današnja sira',
  'notif.body': 'Kratak događaj iz života Poslanika ﷺ čeka te.',

  'honorific.saw': 'neka je na njega Allahov blagoslov i mir',
  'honorific.ra': 'Allah njime bio zadovoljan',
  'honorific.raha': 'Allah njome bio zadovoljan',
  'honorific.rh': 'Allah mu se smilovao',

  'error.title': 'Nešto nije u redu',
  'error.body': 'Tvoj napredak je siguran. Pokušaj ponovo.',
  'notFound.title': 'Stranica nije pronađena',
  'notFound.home': 'Na početnu',

  'a11y.back': 'Nazad',
  'a11y.progress': 'Napredak {percent} posto',
  'a11y.selected': 'odabrano',
  'a11y.correct': 'tačno',
  'a11y.incorrect': 'netačno',
  'a11y.marker': '{name}, {precision}',
  'a11y.step': 'Korak {current} od {total}: {name}',
};

export default bs;
