import type { Dictionary } from './en';

const de: Dictionary = {
  'app.name': 'Sira',
  'app.tagline': 'Eine Reise durch das Leben des Propheten Muhammad ﷺ',

  'common.continue': 'Weiter',
  'common.back': 'Zurück',
  'common.close': 'Schließen',
  'common.done': 'Fertig',
  'common.cancel': 'Abbrechen',
  'common.retry': 'Nochmal versuchen',
  'common.seeAll': 'Alle anzeigen',
  'common.next': 'Weiter',

  'tabs.home': 'Start',
  'tabs.timeline': 'Zeitleiste',
  'tabs.map': 'Karte',
  'tabs.explore': 'Entdecken',
  'tabs.profile': 'Profil',

  'onboarding.step': 'Schritt {current} von {total}',
  'onboarding.welcome.title': 'Sira',
  'onboarding.welcome.body': 'Eine Reise durch das Leben des Propheten Muhammad ﷺ – durch Orte, Menschen, Ereignisse und die Quellen, die sie bewahren.',
  'onboarding.seerah.title': 'Was ist die Sira?',
  'onboarding.seerah.body': 'Die Sira (as-Sīra an-Nabawiyya) ist die Lebensgeschichte des Propheten ﷺ: seine Geburt in Mekka, die Offenbarung, die Jahre der Not, die Hidschra nach Medina und die Gründung der ersten muslimischen Gemeinschaft. Muslime studieren sie, um ihn kennenzulernen und von seinem Vorbild zu lernen.',
  'onboarding.how.title': 'So funktioniert die Reise',
  'onboarding.how.body': 'Zehn Schlüsselepisoden, eine Zeitleiste und eine interaktive Karte. Jede Episode durchläuft sechs Stationen:',
  'onboarding.loop.explore': 'Entdecken',
  'onboarding.loop.explore.desc': 'Orte, Menschen und Ereignisse',
  'onboarding.loop.learn': 'Lernen',
  'onboarding.loop.learn.desc': 'was geschah – aus den Quellen',
  'onboarding.loop.connect': 'Verbinden',
  'onboarding.loop.connect.desc': 'wie alles zusammenhängt',
  'onboarding.loop.think': 'Nachdenken',
  'onboarding.loop.think.desc': 'mit einer kurzen Wissensaufgabe',
  'onboarding.loop.remember': 'Erinnern',
  'onboarding.loop.remember.desc': 'mit sanfter Wiederholung',
  'onboarding.loop.reflect': 'Reflektieren',
  'onboarding.loop.reflect.desc': 'was es für dein Leben bedeutet',
  'onboarding.sources.title': 'Quellen und Genauigkeit',
  'onboarding.sources.body': 'Nichts in dieser App ist erfunden: keine Verse, Hadithe, Dialoge oder Daten. Jede Episode nennt ihre Quellen, und jede Aussage ist gekennzeichnet:',
  'onboarding.sources.note': 'Wo die Quellen voneinander abweichen, sagt die App das. Der Prophet ﷺ wird in keinem Bild dargestellt.',
  'onboarding.language.title': 'Wähle deine Sprache',
  'onboarding.language.body': 'Du kannst sie später in den Einstellungen ändern.',
  'onboarding.start.title': 'Die Reise beginnen',
  'onboarding.start.body': 'Beginne mit der ersten Episode – Geburt und frühes Leben des Propheten ﷺ – oder entdecke frei.',
  'onboarding.start.cta': 'Episode 1 starten',
  'onboarding.start.later': 'Zuerst entdecken',

  'kind.fact': 'Gesicherte Tatsache',
  'kind.fact.desc': 'Belegt durch den Koran, authentische Hadithe oder die Übereinstimmung der Sira-Quellen.',
  'kind.interpretation': 'Historische Deutung',
  'kind.interpretation.desc': 'Eine historische Lesart, ein ungefähres Datum oder ein Punkt, an dem die Quellen abweichen.',
  'kind.reflection': 'Reflexion',
  'kind.reflection.desc': 'Ein Gedanke oder eine Lehre für dich – keine historische Aussage.',

  'era.before': 'Vor dem Prophetentum',
  'era.makkah': 'Mekkanische Zeit',
  'era.madinah': 'Medinensische Zeit',

  'certainty.established': 'Datum gesichert',
  'certainty.approximate': 'Ungefähres Datum',
  'certainty.disputed': 'Datum umstritten',

  'home.greeting': 'As-salamu alaikum',
  'home.continue': 'Reise fortsetzen',
  'home.start': 'Die Reise beginnen',
  'home.allDone': 'Du hast alle zehn Episoden abgeschlossen. Du kannst sie jederzeit wieder besuchen.',
  'home.episodeLabel': 'Episode {number}',
  'home.progress': 'Sira-Fortschritt',
  'home.episodes': '{done} / {total} Episoden',
  'home.explored': '{percent} % entdeckt',
  'home.featured': 'Ausgewähltes Ereignis',
  'home.today': 'Die Sira von heute',
  'home.todayIntro.before': 'Heute entdecken wir ein wichtiges Ereignis aus den Jahren vor dem Prophetentum.',
  'home.todayIntro.makkah': 'Heute entdecken wir ein wichtiges Ereignis aus der mekkanischen Zeit.',
  'home.todayIntro.madinah': 'Heute entdecken wir ein wichtiges Ereignis aus der medinensischen Zeit.',
  'home.learnMore': 'Mehr erfahren',
  'home.dailyQuestion': 'Tagesfrage',
  'home.dailyDone': 'Heute beantwortet – morgen gibt es eine neue Frage.',
  'home.recentPlaces': 'Zuletzt entdeckte Orte',
  'home.recentNone': 'Orte, die du in Episoden und auf der Karte entdeckst, erscheinen hier.',
  'home.review': 'Wiederholungszentrum',
  'home.reviewDue': '{count} zu wiederholen',
  'home.reviewNone': 'Nichts fällig',
  'home.search': 'Personen, Orte, Ereignisse suchen …',

  'timeline.title': 'Zeitleiste',
  'timeline.subtitle': 'Das Leben des Propheten ﷺ der Reihe nach. Als ungefähr oder umstritten markierte Daten sind nicht sicher.',
  'timeline.all': 'Alle',
  'timeline.legend': 'Tippe auf ein Ereignis, um Personen, Orte und Quellen zu sehen.',

  'map.title': 'Karte',
  'map.subtitle': 'Wichtige Orte der Sira im Hidschas. Mit zwei Fingern oder den Tasten zoomen, ziehen zum Verschieben.',
  'map.legend': 'Legende',
  'map.historical': 'Historischer Ort',
  'map.historical.desc': 'Der Ort ist sicher bekannt.',
  'map.approximate': 'Ungefährer Ort',
  'map.approximate.desc': 'Die genaue Stelle ist unsicher.',
  'map.modern': 'Heutige Geografie',
  'map.modern.desc': 'Heutiger Bezugspunkt, nur zur Orientierung.',
  'map.route': 'Route (ungefähr)',
  'map.coast': 'Rotes Meer – heutige Küstenlinie (ungefähr)',
  'map.zoomIn': 'Vergrößern',
  'map.zoomOut': 'Verkleinern',
  'map.reset': 'Ansicht zurücksetzen',
  'map.routes': 'Routen',
  'map.showRoutes': 'Routen anzeigen',
  'map.whyItMatters': 'Warum der Ort wichtig ist',
  'map.events': 'Zugehörige Ereignisse',
  'map.people': 'Zugehörige Personen',
  'map.episodes': 'Episoden',
  'map.howKnown': 'Woher wir wissen, wo er liegt',
  'map.distance': 'Etwa {km} km von Mekka (Luftlinie, heutige Messung)',
  'map.openPlace': 'Ort öffnen',
  'map.offMap': 'Außerhalb dieser Karte: {place}',
  'map.label': 'Karte des Hidschas mit {count} Orten',

  'explore.title': 'Entdecken',
  'explore.subtitle': 'Personen, Orte, Ereignisse und Themen der Sira – und wie sie zusammenhängen.',
  'explore.people': 'Personen',
  'explore.places': 'Orte',
  'explore.events': 'Ereignisse',
  'explore.themes': 'Themen',
  'explore.episodes': 'Episoden',
  'explore.bookmarks': 'Meine Lesezeichen',
  'explore.review': 'Wiederholungszentrum',
  'explore.search': 'Suche',

  'search.title': 'Suche',
  'search.placeholder': 'Episoden, Personen, Orte suchen …',
  'search.hint': 'Versuche „Bilal“, „Hidschra“ oder „Badr“.',
  'search.empty': 'Nichts gefunden für „{query}“.',
  'search.related': 'Verwandt',
  'search.clear': 'Suche löschen',

  'type.episode': 'Episode',
  'type.event': 'Ereignis',
  'type.person': 'Person',
  'type.place': 'Ort',
  'type.theme': 'Thema',
  'type.source': 'Quelle',

  'connections.title': 'Wie hängt alles zusammen?',
  'connections.subtitle': 'Tippe auf eine Karte, um der Verbindung zu folgen.',
  'connections.chain': 'Ereignis → Personen → Orte → Verwandte Ereignisse',

  'episode.label': 'Episode {number}',
  'episode.start': 'Episode starten',
  'episode.continue': 'Episode fortsetzen',
  'episode.restart': 'Erneut erkunden',
  'episode.completed': 'Abgeschlossen',
  'episode.bestScore': 'Bestes Quiz-Ergebnis: {percent} %',
  'episode.notFound': 'Diese Episode wurde nicht gefunden.',
  'episode.stepOf': '{current} von {total}',
  'episode.next': 'Weiter',
  'episode.finish': 'Episode abschließen',
  'episode.overview': 'In dieser Episode',
  'episode.step.introduction': 'Einleitung',
  'episode.step.context': 'Historischer Hintergrund',
  'episode.step.timeline': 'Zeitleiste',
  'episode.step.mainEvent': 'Hauptereignis',
  'episode.step.people': 'Beteiligte Personen',
  'episode.step.locations': 'Orte',
  'episode.step.explore': 'Interaktive Erkundung',
  'episode.step.challenge': 'Wissensaufgabe',
  'episode.step.lesson': 'Lehren',
  'episode.step.reflection': 'Denk darüber nach',
  'episode.step.sources': 'Quellen',
  'episode.tapToDiscover': 'Tippe auf jede Karte, um sie zu öffnen und zu deinen Entdeckungen hinzuzufügen.',
  'episode.discovered': 'Entdeckt',
  'episode.mapHint': 'Die Orte dieser Episode. Tippe auf eine Markierung, um mehr zu erfahren.',
  'episode.challengeIntro': '{count} Fragen zu dieser Episode. Fehler werden für die spätere Wiederholung gespeichert – es gibt kein Zeitlimit.',
  'episode.challengeStart': 'Aufgabe starten',
  'episode.challengeResult': '{correct} von {total} richtig',
  'episode.challengeRetry': 'Verpasste Fragen wurden deinem Wiederholungszentrum hinzugefügt.',
  'episode.doneTitle': 'Episode abgeschlossen',
  'episode.doneBody': 'Du hast „{title}“ abgeschlossen.',
  'episode.points': '+{points} Wissenspunkte',
  'episode.nextEpisode': 'Nächste Episode',
  'episode.backHome': 'Zur Startseite',
  'episode.mainEvent': 'Hauptereignis',

  'narration.play': 'Erzählung anhören',
  'narration.pause': 'Erzählung pausieren',

  'reflection.title': 'Denk darüber nach',
  'reflection.note': 'Deine Gedanken bleiben auf diesem Gerät und werden nie bewertet.',
  'reflection.write': 'Gedanken aufschreiben',
  'reflection.select': 'Oder wähle einen aus',
  'reflection.placeholder': 'Deine Gedanken …',
  'reflection.save': 'Gedanken speichern',
  'reflection.saved': 'Gespeichert',
  'reflection.skip': 'Einfach weiter',
  'reflection.clear': 'Gedanken entfernen',

  'sources.primary': 'Primärquellen',
  'sources.secondary': 'Sekundäre historische Quellen',
  'sources.further': 'Weiterführende Literatur',
  'sources.open': 'Quelle öffnen',
  'sources.openHint': 'Öffnet {host} im Browser.',
  'source.type.quran': 'Koran',
  'source.type.hadith': 'Hadith',
  'source.type.seerah': 'Sira',
  'source.type.history': 'Geschichte',
  'source.type.biography': 'Biografie',

  'person.role': 'Rolle',
  'person.relationship': 'Beziehung',
  'person.biography': 'Biografie',
  'person.events': 'Ereignisse',
  'person.episodes': 'Episoden',
  'person.notFound': 'Diese Person wurde nicht gefunden.',

  'event.date': 'Datum',
  'event.summary': 'Zusammenfassung',
  'event.people': 'Personen',
  'event.places': 'Orte',
  'event.episode': 'Zugehörige Episode',
  'event.related': 'Verwandte Ereignisse',
  'event.sources': 'Quellen',
  'event.themes': 'Themen',
  'event.notFound': 'Dieses Ereignis wurde nicht gefunden.',

  'place.description': 'Über diesen Ort',
  'place.notFound': 'Dieser Ort wurde nicht gefunden.',
  'place.showOnMap': 'Auf der Karte zeigen',

  'theme.events': 'Ereignisse',
  'theme.episodes': 'Episoden',
  'theme.notFound': 'Dieses Thema wurde nicht gefunden.',

  'bookmark.add': 'Lesezeichen setzen',
  'bookmark.remove': 'Lesezeichen entfernen',
  'bookmarks.title': 'Meine Lesezeichen',
  'bookmarks.empty': 'Noch keine Lesezeichen. Nutze das Lesezeichen-Symbol bei Episoden, Ereignissen, Personen, Orten und Quellen.',

  'review.title': 'Wiederholungszentrum',
  'review.subtitle': 'Verpasste Fragen kommen nach einer Weile wieder, bis du sie sicher kennst.',
  'review.needs': 'Zu wiederholen',
  'review.mastered': 'Gemeistert',
  'review.recent': 'Kürzlich gelernt',
  'review.start': 'Jetzt wiederholen ({count})',
  'review.dueNow': 'Jetzt fällig',
  'review.nextOn': 'Nächste Wiederholung: {date}',
  'review.missed': '{count}× verpasst',
  'review.emptyNeeds': 'Keine Fragen zu wiederholen. Verpasste Quizfragen erscheinen hier.',
  'review.emptyMastered': 'Fragen, die du mehrmals erfolgreich wiederholt hast, erscheinen hier.',
  'review.emptyRecent': 'Episoden, die du abschließt, und Ereignisse, die du in den letzten 14 Tagen entdeckst, erscheinen hier.',
  'review.doneTitle': 'Wiederholung abgeschlossen',
  'review.doneBody': 'Du hast dir {correct} von {total} gemerkt.',
  'review.nothingDue': 'Gerade ist nichts fällig.',

  'quiz.correct': 'Richtig',
  'quiz.notQuite': 'Nicht ganz',
  'quiz.correctAnswer': 'Richtige Antwort: {answer}',
  'quiz.addedToReview': 'Im Wiederholungszentrum gespeichert.',
  'quiz.true': 'Richtig',
  'quiz.false': 'Falsch',
  'quiz.check': 'Prüfen',
  'quiz.ordering.hint': 'Tippe die Einträge in der richtigen Reihenfolge an.',
  'quiz.ordering.reset': 'Neu beginnen',
  'quiz.matching.hint': 'Tippe links einen Eintrag an, dann seinen Partner rechts.',
  'quiz.matching.mistakes': 'Fehler: {count}',
  'quiz.question': 'Frage {current} von {total}',
  'quiz.kind.general': 'Frage',
  'quiz.kind.timeline': 'Zeitleiste ordnen',
  'quiz.kind.sequence': 'Was kam zuerst?',
  'quiz.kind.connection': 'Verbindung',
  'quiz.kind.personEvent': 'Person → Ereignis',
  'quiz.kind.placeEvent': 'Ort → Ereignis',
  'quiz.kind.eventLesson': 'Ereignis → Lehre',

  'profile.title': 'Profil',
  'profile.progress': 'Sira-Fortschritt',
  'profile.points': 'Wissenspunkte',
  'profile.completed': 'Abgeschlossene Episoden',
  'profile.noneCompleted': 'Noch keine Episode abgeschlossen.',
  'profile.quizResults': 'Quiz-Ergebnisse',
  'profile.noQuiz': 'Deine Quiz-Ergebnisse erscheinen hier.',
  'profile.badges': 'Entdecker-Abzeichen',
  'profile.bookmarks': 'Lesezeichen',
  'profile.reflections': 'Gedanken',
  'profile.settings': 'Einstellungen',
  'profile.review': 'Wiederholungszentrum',
  'stats.episodes': 'Episoden',
  'stats.events': 'Entdeckte Ereignisse',
  'stats.people': 'Entdeckte Personen',
  'stats.places': 'Entdeckte Orte',
  'badges.locked': 'Noch nicht verdient',
  'badges.earned': 'Verdient am {date}',
  'badge.first_journey.name': 'Erste Reise',
  'badge.first_journey.desc': 'Schließe deine erste Episode ab.',
  'badge.makkah_explorer.name': 'Mekka-Entdecker',
  'badge.makkah_explorer.desc': 'Schließe alle Episoden der mekkanischen Zeit ab.',
  'badge.madinah_explorer.name': 'Medina-Entdecker',
  'badge.madinah_explorer.desc': 'Schließe alle Episoden der medinensischen Zeit ab.',
  'badge.timeline_explorer.name': 'Zeitleisten-Entdecker',
  'badge.timeline_explorer.desc': 'Entdecke jedes Ereignis der Zeitleiste.',
  'badge.history_seeker.name': 'Geschichtssucher',
  'badge.history_seeker.desc': 'Entdecke jede Person der Personendatenbank.',
  'badge.reflective_mind.name': 'Nachdenklicher Geist',
  'badge.reflective_mind.desc': 'Speichere fünf Gedanken.',
  'badge.seerah_student.name': 'Sira-Schüler',
  'badge.seerah_student.desc': 'Schließe fünf Episoden mit mindestens 70 % im Quiz ab.',
  'badge.ten_episodes.name': '10 Episoden abgeschlossen',
  'badge.ten_episodes.desc': 'Schließe alle zehn Episoden ab.',
  'celebrate.title': 'Neues Abzeichen',

  'settings.title': 'Einstellungen',
  'settings.general': 'Allgemein',
  'settings.language': 'Sprache',
  'settings.appearance': 'Darstellung',
  'settings.theme': 'Dunkler Modus',
  'settings.theme.system': 'System',
  'settings.theme.light': 'Hell',
  'settings.theme.dark': 'Dunkel',
  'settings.sound': 'Töne',
  'settings.haptics': 'Vibration',
  'settings.notifications': 'Benachrichtigungen',
  'settings.reminder': 'Tägliche Erinnerung an die Sira von heute',
  'settings.reminderDesc': 'Eine sanfte Erinnerung pro Tag. Optional – die App funktioniert auch ohne.',
  'settings.reminderTime': 'Uhrzeit der Erinnerung: {time}',
  'settings.notifDenied': 'Benachrichtigungen sind für diese App in den Systemeinstellungen ausgeschaltet.',
  'settings.notifUnavailable': 'Benachrichtigungen sind auf diesem Gerät nicht verfügbar.',
  'settings.accessibility': 'Barrierefreiheit',
  'settings.largeText': 'Größere Schrift',
  'settings.highContrast': 'Hoher Kontrast',
  'settings.reducedMotion': 'Bewegung reduzieren',
  'settings.info': 'Informationen',
  'settings.about': 'Über die App',
  'settings.privacy': 'Datenschutz',
  'settings.sources': 'Quellen',
  'settings.data': 'Daten',
  'settings.reset': 'Fortschritt zurücksetzen',
  'settings.resetDesc': 'Löscht abgeschlossene Episoden, Quiz-Ergebnisse, Lesezeichen, Gedanken und Entdeckungen auf diesem Gerät.',
  'settings.resetTitle': 'Gesamten Fortschritt zurücksetzen?',
  'settings.resetBody': 'Das kann nicht rückgängig gemacht werden.',
  'settings.resetConfirm': 'Ja, zurücksetzen',
  'settings.version': 'Version {version}',

  'about.title': 'Über Sira',
  'about.p1': 'Sira ist eine kostenlose Lern-App über das Leben des Propheten Muhammad ﷺ für Jugendliche und Erwachsene. Version 1 umfasst zehn Schlüsselepisoden; weitere können ohne Änderung der App ergänzt werden.',
  'about.p2': 'Sie enthält keine Werbung, keine Käufe und keine Konten und funktioniert vollständig offline.',
  'about.p3': 'Die App ist eine Einführung, kein wissenschaftliches Nachschlagewerk. Jede Aussage ist als gesicherte Tatsache, historische Deutung oder Reflexion gekennzeichnet, und die Quellen sind angegeben, damit du weiterlesen kannst. Bei religiösen Fragen wende dich an qualifizierte Gelehrte.',
  'privacy.title': 'Datenschutz',
  'privacy.p1': 'Es ist kein Konto nötig. Es werden keine persönlichen Daten gesammelt, gesendet oder verkauft. Es gibt keine Werbung, keine Analyse und kein Tracking, und die App stellt keine Netzwerkverbindungen her.',
  'privacy.p2': 'Fortschritt, Quiz-Ergebnisse, Lesezeichen und Gedanken werden nur auf diesem Gerät gespeichert. „Fortschritt zurücksetzen“ löscht sie. Quellenlinks öffnen sich nur im Browser, wenn du sie antippst.',
  'sourcesPage.title': 'Quellen',
  'sourcesPage.p1': 'Die Inhalte beruhen auf dem Koran, den Hadithsammlungen Sahih al-Bukhari, Sahih Muslim und Sunan Ibn Madscha, der Sira von Ibn Hischam (nach Ibn Ishaq), Ibn Saʿd, at-Tabari, Ibn Kathir und Ibn al-Qayyim sowie modernen Biografien.',
  'sourcesPage.p2': 'Koranangaben verweisen auf quran.com, Bukhari-Angaben auf sunnah.com. Keine Angabe wurde erfunden; wo ein Detail nicht überprüft werden konnte, wurde es weggelassen.',
  'sourcesPage.p3': 'Kartenpositionen nutzen heutige Koordinaten. Orte, deren genaue Lage unsicher ist, sind als ungefähr markiert, und Routen werden nur als allgemeine Richtung gezeigt.',

  'notif.channel': 'Die Sira von heute',
  'notif.title': 'Die Sira von heute',
  'notif.body': 'Ein kurzes Ereignis aus dem Leben des Propheten ﷺ wartet auf dich.',

  'honorific.saw': 'Allahs Segen und Frieden seien auf ihm',
  'honorific.ra': 'möge Allah mit ihm zufrieden sein',
  'honorific.raha': 'möge Allah mit ihr zufrieden sein',
  'honorific.rh': 'möge Allah sich seiner erbarmen',

  'error.title': 'Etwas ist schiefgelaufen',
  'error.body': 'Dein Fortschritt ist sicher. Bitte versuche es erneut.',
  'notFound.title': 'Seite nicht gefunden',
  'notFound.home': 'Zur Startseite',

  'a11y.back': 'Zurück',
  'a11y.progress': 'Fortschritt {percent} Prozent',
  'a11y.selected': 'ausgewählt',
  'a11y.correct': 'richtig',
  'a11y.incorrect': 'falsch',
  'a11y.marker': '{name}, {precision}',
  'a11y.step': 'Schritt {current} von {total}: {name}',
};

export default de;
