const en = {
  'app.name': 'Sira',
  'app.tagline': 'Journey through the life of the Prophet Muhammad ﷺ',

  'common.continue': 'Continue',
  'common.back': 'Back',
  'common.close': 'Close',
  'common.done': 'Done',
  'common.cancel': 'Cancel',
  'common.retry': 'Try again',
  'common.seeAll': 'See all',
  'common.next': 'Next',

  'tabs.home': 'Home',
  'tabs.timeline': 'Timeline',
  'tabs.map': 'Map',
  'tabs.explore': 'Explore',
  'tabs.profile': 'Profile',

  'onboarding.step': 'Step {current} of {total}',
  'onboarding.welcome.title': 'Sira',
  'onboarding.welcome.body': 'A journey through the life of the Prophet Muhammad ﷺ – through places, people, events and the sources that preserve them.',
  'onboarding.seerah.title': 'What is the Seerah?',
  'onboarding.seerah.body': 'The Seerah (al-Sīrah al-Nabawiyyah) is the life story of the Prophet ﷺ: his birth in Makkah, the revelation, the years of hardship, the Hijrah to Madinah and the founding of the first Muslim community. Muslims study it to know him and to learn from his example.',
  'onboarding.how.title': 'How the journey works',
  'onboarding.how.body': 'Ten key episodes, a timeline and an interactive map. Each episode moves through six stages:',
  'onboarding.loop.explore': 'Explore',
  'onboarding.loop.explore.desc': 'places, people and events',
  'onboarding.loop.learn': 'Learn',
  'onboarding.loop.learn.desc': 'what happened, from the sources',
  'onboarding.loop.connect': 'Connect',
  'onboarding.loop.connect.desc': 'how everything fits together',
  'onboarding.loop.think': 'Think',
  'onboarding.loop.think.desc': 'with a short knowledge challenge',
  'onboarding.loop.remember': 'Remember',
  'onboarding.loop.remember.desc': 'with gentle review over time',
  'onboarding.loop.reflect': 'Reflect',
  'onboarding.loop.reflect.desc': 'on what it means for your life',
  'onboarding.sources.title': 'Sources and accuracy',
  'onboarding.sources.body': 'Nothing in this app is invented: no verses, hadith, dialogue or dates. Every episode lists its sources, and every statement is labelled:',
  'onboarding.sources.note': 'Where the sources differ, the app says so. The Prophet ﷺ is never depicted in any image.',
  'onboarding.language.title': 'Choose your language',
  'onboarding.language.body': 'You can change it later in the settings.',
  'onboarding.start.title': 'Begin the journey',
  'onboarding.start.body': 'Start with the first episode – the birth and early life of the Prophet ﷺ – or explore freely.',
  'onboarding.start.cta': 'Start episode 1',
  'onboarding.start.later': 'Explore first',

  'kind.fact': 'Established fact',
  'kind.fact.desc': 'Stated by the Quran, authentic hadith or the agreement of the Seerah sources.',
  'kind.interpretation': 'Historical interpretation',
  'kind.interpretation.desc': 'A historical reading, an approximate date or a point where sources differ.',
  'kind.reflection': 'Reflection',
  'kind.reflection.desc': 'A thought or lesson for you – not a historical claim.',

  'era.before': 'Before prophethood',
  'era.makkah': 'Makkan period',
  'era.madinah': 'Madinan period',

  'certainty.established': 'Date established',
  'certainty.approximate': 'Approximate date',
  'certainty.disputed': 'Date disputed',

  'home.greeting': 'As-salamu alaykum',
  'home.continue': 'Continue journey',
  'home.start': 'Begin the journey',
  'home.allDone': 'You have completed all ten episodes. Revisit them anytime.',
  'home.episodeLabel': 'Episode {number}',
  'home.progress': 'Seerah progress',
  'home.episodes': '{done} / {total} episodes',
  'home.explored': '{percent}% explored',
  'home.featured': 'Featured event',
  'home.today': "Today's Seerah",
  'home.todayIntro.before': 'Today we explore an important event from the years before prophethood.',
  'home.todayIntro.makkah': 'Today we explore an important event from the Makkan period.',
  'home.todayIntro.madinah': 'Today we explore an important event from the Madinan period.',
  'home.learnMore': 'Learn more',
  'home.dailyQuestion': 'Daily question',
  'home.dailyDone': 'Answered today – a new question tomorrow.',
  'home.recentPlaces': 'Recently explored locations',
  'home.recentNone': 'Places you discover in episodes and on the map appear here.',
  'home.review': 'Review Center',
  'home.reviewDue': '{count} to review',
  'home.reviewNone': 'Nothing due',
  'home.search': 'Search people, places, events…',

  'timeline.title': 'Timeline',
  'timeline.subtitle': 'The life of the Prophet ﷺ in order. Dates marked as approximate or disputed are not certain.',
  'timeline.all': 'All',
  'timeline.legend': 'Tap an event to see its people, places and sources.',

  'map.title': 'Map',
  'map.subtitle': 'Key places of the Seerah in the Hijaz. Pinch or use the buttons to zoom; drag to move.',
  'map.legend': 'Legend',
  'map.historical': 'Historical location',
  'map.historical.desc': 'The site is securely identified.',
  'map.approximate': 'Approximate location',
  'map.approximate.desc': 'The exact spot is uncertain.',
  'map.modern': 'Modern geography',
  'map.modern.desc': 'Present-day reference for orientation only.',
  'map.route': 'Route (approximate)',
  'map.coast': 'Red Sea – modern coastline (approximate)',
  'map.zoomIn': 'Zoom in',
  'map.zoomOut': 'Zoom out',
  'map.reset': 'Reset view',
  'map.routes': 'Routes',
  'map.showRoutes': 'Show routes',
  'map.whyItMatters': 'Why it matters',
  'map.events': 'Related events',
  'map.people': 'Related people',
  'map.episodes': 'Episodes',
  'map.howKnown': 'How we know where it is',
  'map.distance': 'About {km} km from Makkah (straight line, modern measurement)',
  'map.openPlace': 'Open place',
  'map.offMap': 'Outside this map: {place}',
  'map.label': 'Map of the Hijaz with {count} locations',

  'explore.title': 'Explore',
  'explore.subtitle': 'People, places, events and themes of the Seerah – and how they connect.',
  'explore.people': 'People',
  'explore.places': 'Places',
  'explore.events': 'Events',
  'explore.themes': 'Themes',
  'explore.episodes': 'Episodes',
  'explore.bookmarks': 'My Bookmarks',
  'explore.review': 'Review Center',
  'explore.search': 'Search',

  'search.title': 'Search',
  'search.placeholder': 'Search episodes, people, places…',
  'search.hint': 'Try "Bilal", "Hijrah" or "Badr".',
  'search.empty': 'Nothing found for "{query}".',
  'search.related': 'Related',
  'search.clear': 'Clear search',

  'type.episode': 'Episode',
  'type.event': 'Event',
  'type.person': 'Person',
  'type.place': 'Place',
  'type.theme': 'Theme',
  'type.source': 'Source',

  'connections.title': 'How is everything connected?',
  'connections.subtitle': 'Tap any card to follow the connection.',
  'connections.chain': 'Event → People → Places → Related events',

  'episode.label': 'Episode {number}',
  'episode.start': 'Start episode',
  'episode.continue': 'Continue episode',
  'episode.restart': 'Explore again',
  'episode.completed': 'Completed',
  'episode.bestScore': 'Best quiz score: {percent}%',
  'episode.notFound': 'This episode could not be found.',
  'episode.stepOf': '{current} of {total}',
  'episode.next': 'Next',
  'episode.finish': 'Complete episode',
  'episode.overview': 'In this episode',
  'episode.step.introduction': 'Introduction',
  'episode.step.context': 'Historical context',
  'episode.step.timeline': 'Timeline',
  'episode.step.mainEvent': 'Main event',
  'episode.step.people': 'People involved',
  'episode.step.locations': 'Locations',
  'episode.step.explore': 'Interactive exploration',
  'episode.step.challenge': 'Knowledge challenge',
  'episode.step.lesson': 'Lessons',
  'episode.step.reflection': 'Think about it',
  'episode.step.sources': 'Sources',
  'episode.tapToDiscover': 'Tap each card to open it and add it to your discoveries.',
  'episode.discovered': 'Discovered',
  'episode.mapHint': 'The locations of this episode. Tap a marker to learn more.',
  'episode.challengeIntro': '{count} questions about this episode. Mistakes are saved for later review – there is no time limit.',
  'episode.challengeStart': 'Start the challenge',
  'episode.challengeResult': '{correct} of {total} correct',
  'episode.challengeRetry': 'Missed questions were added to your Review Center.',
  'episode.doneTitle': 'Episode complete',
  'episode.doneBody': 'You completed "{title}".',
  'episode.points': '+{points} knowledge points',
  'episode.nextEpisode': 'Next episode',
  'episode.backHome': 'Back to home',
  'episode.mainEvent': 'Main event',

  'narration.play': 'Listen to narration',
  'narration.pause': 'Pause narration',

  'reflection.title': 'Think about it',
  'reflection.note': 'Your reflections stay on this device and are never judged.',
  'reflection.write': 'Write a reflection',
  'reflection.select': 'Or choose one',
  'reflection.placeholder': 'Your thoughts…',
  'reflection.save': 'Save reflection',
  'reflection.saved': 'Saved',
  'reflection.skip': 'Simply continue',
  'reflection.clear': 'Remove reflection',

  'sources.primary': 'Primary sources',
  'sources.secondary': 'Secondary historical sources',
  'sources.further': 'Further reading',
  'sources.open': 'Open reference',
  'sources.openHint': 'Opens {host} in your browser.',
  'source.type.quran': 'Quran',
  'source.type.hadith': 'Hadith',
  'source.type.seerah': 'Seerah',
  'source.type.history': 'History',
  'source.type.biography': 'Biography',

  'person.role': 'Role',
  'person.relationship': 'Relationship',
  'person.biography': 'Biography',
  'person.events': 'Events',
  'person.episodes': 'Episodes',
  'person.notFound': 'This person could not be found.',

  'event.date': 'Date',
  'event.summary': 'Summary',
  'event.people': 'People',
  'event.places': 'Locations',
  'event.episode': 'Related episode',
  'event.related': 'Related events',
  'event.sources': 'Sources',
  'event.themes': 'Themes',
  'event.notFound': 'This event could not be found.',

  'place.description': 'About this place',
  'place.notFound': 'This place could not be found.',
  'place.showOnMap': 'Show on map',

  'theme.events': 'Events',
  'theme.episodes': 'Episodes',
  'theme.notFound': 'This theme could not be found.',

  'bookmark.add': 'Add bookmark',
  'bookmark.remove': 'Remove bookmark',
  'bookmarks.title': 'My Bookmarks',
  'bookmarks.empty': 'Nothing bookmarked yet. Use the bookmark icon on episodes, events, people, places and sources.',

  'review.title': 'Review Center',
  'review.subtitle': 'Questions you missed come back after a while until you know them well.',
  'review.needs': 'Needs Review',
  'review.mastered': 'Mastered',
  'review.recent': 'Recently Learned',
  'review.start': 'Review now ({count})',
  'review.dueNow': 'Due now',
  'review.nextOn': 'Next review: {date}',
  'review.missed': 'Missed {count}×',
  'review.emptyNeeds': 'No questions need review. Missed quiz questions will appear here.',
  'review.emptyMastered': 'Questions you have reviewed successfully several times will appear here.',
  'review.emptyRecent': 'Episodes you complete and events you discover in the last 14 days appear here.',
  'review.doneTitle': 'Review complete',
  'review.doneBody': 'You remembered {correct} of {total}.',
  'review.nothingDue': 'Nothing is due right now.',

  'quiz.correct': 'Correct',
  'quiz.notQuite': 'Not quite',
  'quiz.correctAnswer': 'Correct answer: {answer}',
  'quiz.addedToReview': 'Saved to your Review Center.',
  'quiz.true': 'True',
  'quiz.false': 'False',
  'quiz.check': 'Check',
  'quiz.ordering.hint': 'Tap the items in the right order.',
  'quiz.ordering.reset': 'Start over',
  'quiz.matching.hint': 'Tap an item on the left, then its match on the right.',
  'quiz.matching.mistakes': 'Mistakes: {count}',
  'quiz.question': 'Question {current} of {total}',
  'quiz.kind.general': 'Question',
  'quiz.kind.timeline': 'Timeline ordering',
  'quiz.kind.sequence': 'Which came first?',
  'quiz.kind.connection': 'Connection',
  'quiz.kind.personEvent': 'Person → Event',
  'quiz.kind.placeEvent': 'Place → Event',
  'quiz.kind.eventLesson': 'Event → Lesson',

  'profile.title': 'Profile',
  'profile.progress': 'Seerah progress',
  'profile.points': 'Knowledge points',
  'profile.completed': 'Completed episodes',
  'profile.noneCompleted': 'No episodes completed yet.',
  'profile.quizResults': 'Quiz results',
  'profile.noQuiz': 'Your quiz results will appear here.',
  'profile.badges': 'Explorer badges',
  'profile.bookmarks': 'Bookmarks',
  'profile.reflections': 'Reflections',
  'profile.settings': 'Settings',
  'profile.review': 'Review Center',
  'stats.episodes': 'Episodes',
  'stats.events': 'Events discovered',
  'stats.people': 'People discovered',
  'stats.places': 'Locations discovered',
  'badges.locked': 'Not yet earned',
  'badges.earned': 'Earned on {date}',
  'badge.first_journey.name': 'First Journey',
  'badge.first_journey.desc': 'Complete your first episode.',
  'badge.makkah_explorer.name': 'Makkah Explorer',
  'badge.makkah_explorer.desc': 'Complete all episodes of the Makkan period.',
  'badge.madinah_explorer.name': 'Madinah Explorer',
  'badge.madinah_explorer.desc': 'Complete all episodes of the Madinan period.',
  'badge.timeline_explorer.name': 'Timeline Explorer',
  'badge.timeline_explorer.desc': 'Discover every event on the timeline.',
  'badge.history_seeker.name': 'History Seeker',
  'badge.history_seeker.desc': 'Discover every person in the people database.',
  'badge.reflective_mind.name': 'Reflective Mind',
  'badge.reflective_mind.desc': 'Save five reflections.',
  'badge.seerah_student.name': 'Seerah Student',
  'badge.seerah_student.desc': 'Complete five episodes with at least 70% in the quiz.',
  'badge.ten_episodes.name': '10 Episodes Completed',
  'badge.ten_episodes.desc': 'Complete all ten episodes.',
  'celebrate.title': 'New badge',

  'settings.title': 'Settings',
  'settings.general': 'General',
  'settings.language': 'Language',
  'settings.appearance': 'Appearance',
  'settings.theme': 'Dark mode',
  'settings.theme.system': 'System',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.sound': 'Sound',
  'settings.haptics': 'Vibration',
  'settings.notifications': 'Notifications',
  'settings.reminder': "Daily reminder for Today's Seerah",
  'settings.reminderDesc': 'One gentle reminder per day. Optional – the app works fully without it.',
  'settings.reminderTime': 'Reminder time: {time}',
  'settings.notifDenied': 'Notifications are turned off for this app in the system settings.',
  'settings.notifUnavailable': 'Notifications are not available on this device.',
  'settings.accessibility': 'Accessibility',
  'settings.largeText': 'Larger text',
  'settings.highContrast': 'High contrast',
  'settings.reducedMotion': 'Reduce motion',
  'settings.info': 'Information',
  'settings.about': 'About',
  'settings.privacy': 'Privacy',
  'settings.sources': 'Sources',
  'settings.data': 'Data',
  'settings.reset': 'Reset progress',
  'settings.resetDesc': 'Deletes completed episodes, quiz results, bookmarks, reflections and discoveries on this device.',
  'settings.resetTitle': 'Reset all progress?',
  'settings.resetBody': 'This cannot be undone.',
  'settings.resetConfirm': 'Yes, reset',
  'settings.version': 'Version {version}',

  'about.title': 'About Sira',
  'about.p1': 'Sira is a free educational app about the life of the Prophet Muhammad ﷺ for teenagers and adults. Version 1 covers ten key episodes; more can be added without changing the app.',
  'about.p2': 'It contains no advertising, no purchases and no accounts, and it works completely offline.',
  'about.p3': 'The app is an introduction, not a scholarly reference. Every statement is labelled as established fact, historical interpretation or reflection, and the sources are listed so you can read further. For religious questions, consult qualified scholars.',
  'privacy.title': 'Privacy',
  'privacy.p1': 'No account is needed. No personal data is collected, sent or sold. There is no advertising, analytics or tracking, and the app makes no network connections.',
  'privacy.p2': 'Your progress, quiz results, bookmarks and reflections are stored only on this device. "Reset progress" deletes them. Reference links open in your browser only when you tap them.',
  'sourcesPage.title': 'Sources',
  'sourcesPage.p1': 'The content is based on the Quran, the hadith collections Sahih al-Bukhari, Sahih Muslim and Sunan Ibn Majah, the Seerah of Ibn Hisham (from Ibn Ishaq), Ibn Saʿd, al-Tabari, Ibn Kathir and Ibn al-Qayyim, and modern biographies.',
  'sourcesPage.p2': 'Quran references point to quran.com and Bukhari references to sunnah.com. No reference has been invented; where a detail could not be verified, it was left out.',
  'sourcesPage.p3': 'Map positions use modern coordinates. Places whose exact location is uncertain are marked as approximate, and routes are only shown as general directions.',

  'notif.channel': "Today's Seerah",
  'notif.title': "Today's Seerah",
  'notif.body': 'A short event from the life of the Prophet ﷺ is waiting for you.',

  'honorific.saw': 'peace and blessings be upon him',
  'honorific.ra': 'may Allah be pleased with him',
  'honorific.raha': 'may Allah be pleased with her',
  'honorific.rh': 'may Allah have mercy on him',

  'error.title': 'Something went wrong',
  'error.body': 'Your progress is safe. Please try again.',
  'notFound.title': 'Page not found',
  'notFound.home': 'Go to home',

  'a11y.back': 'Back',
  'a11y.progress': 'Progress {percent} percent',
  'a11y.selected': 'selected',
  'a11y.correct': 'correct',
  'a11y.incorrect': 'incorrect',
  'a11y.marker': '{name}, {precision}',
  'a11y.step': 'Step {current} of {total}: {name}',
} as const;

export type TranslationKey = keyof typeof en;
export type Dictionary = Record<TranslationKey, string>;

export default en as Dictionary;
